// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdc0L6gtuhnxEwu1AENYqJXEqRhTORYJw',
    appId: '1:575394412821:web:557f10d2b9c4f70085511c',
    messagingSenderId: '575394412821',
    projectId: 'qikpark-d205a',
    authDomain: 'qikpark-d205a.firebaseapp.com',
    storageBucket: 'qikpark-d205a.firebasestorage.app',
    measurementId: 'G-B48G9C2Z5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzwsq4JpiLBsWU-xUM6sBcy9dprKdehoE',
    appId: '1:575394412821:android:60c4e62c8513e10e85511c',
    messagingSenderId: '575394412821',
    projectId: 'qikpark-d205a',
    storageBucket: 'qikpark-d205a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIeY7twagNpc3Y8_9NSyaG_kG7jZZ8RYs',
    appId: '1:575394412821:ios:9d9eba02124d67ec85511c',
    messagingSenderId: '575394412821',
    projectId: 'qikpark-d205a',
    storageBucket: 'qikpark-d205a.firebasestorage.app',
    androidClientId: '575394412821-lrn8nbb5o77qehi2nbjvtbgrn8pd29je.apps.googleusercontent.com',
    iosClientId: '575394412821-16sqsn3l07u4rq7hnsm7papjk5iadpk0.apps.googleusercontent.com',
    iosBundleId: 'com.nxtdesigns.easypark',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIeY7twagNpc3Y8_9NSyaG_kG7jZZ8RYs',
    appId: '1:575394412821:ios:91e25a51ca95d5a785511c',
    messagingSenderId: '575394412821',
    projectId: 'qikpark-d205a',
    storageBucket: 'qikpark-d205a.firebasestorage.app',
    androidClientId: '575394412821-lrn8nbb5o77qehi2nbjvtbgrn8pd29je.apps.googleusercontent.com',
    iosClientId: '575394412821-rafjq6s2uq9ombb8t98v91s7itnvgd6a.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyHome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdc0L6gtuhnxEwu1AENYqJXEqRhTORYJw',
    appId: '1:575394412821:web:68a0f278c7fd378b85511c',
    messagingSenderId: '575394412821',
    projectId: 'qikpark-d205a',
    authDomain: 'qikpark-d205a.firebaseapp.com',
    storageBucket: 'qikpark-d205a.firebasestorage.app',
    measurementId: 'G-21X3SM1BQ4',
  );
}
